## -*- encoding: utf-8 -*-
## This file (./digInTheDerivativeViaLimits-figure0.sagetex.sage) was *autogenerated* from ./digInTheDerivativeViaLimits-figure0.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('./digInTheDerivativeViaLimits-figure0', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
